#!/bin/bash

# testsフォルダに入れておくファイル
# テストに失敗したときにどの行が違ったか diff コマンドで確かめる
# テスト1に失敗して違いを確認したい場合
# bash $ tests/case 1

i=$1
if [ -d tests ] ; then
    d=tests/
fi
if [ -f $d$i.out -a -f $d$i.correct ] ; then
    diff -u $d$i.out $d$i.correct
    cat <<EOF

上のような違いがある．
-で始まる行を出力しないように変更しなさい．
+で始まる行を出力するように変更しなさい．
EOF
else
    ls $d$i.out $d$i.correct
    echo 違いを調べるファイルが足りない．
fi

example=<<EOS
$ tests/case 1
--- tests/1.correct   2023-09-20 18:35:56.000000000 +0900
+++ tests/1.out       2023-09-27 14:36:48.873409200 +0900
@@ -1,5 +1,5 @@
-Hello world!
-Hello world!
-Hello world!
-Hello world!
-Hello world!
+hello world
+hello world
+hello world
+hello world
+hello world
EOS

